---
title: "Big Data Proj 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
```

```{r cars}
setwd("~/Documents/development/CSCI_3907/Project 1/")

read_project_files <- function(data_path){
  ego_networks <- lapply(list.files(path=data_path, pattern = '*.edges'), function(edgelist){
    read.table(paste(data_path, edgelist, sep=''))
  })
  return(ego_networks)
}

graphs <- read_project_files('~/Documents/development/CSCI_3907/Project 1/data/facebook/')

```

```{r}
parseMainGraph <- function(graphs){
  
  #Placeholder graph
  combined_graph <- data.frame()
  
  #Merge each of the egonetworks into a single dataframe
  for (el in graphs){
    combined_graph <- rbind(combined_graph, el)
  }
  
  #Make graph from the combined dataframe of all ego networks.
  cg <- graph_from_data_frame(combined_graph, directed = FALSE)
  
  #Simplify the input graph removing the loops and multiple edges.
  simplified_graph <- simplify(cg)
  
  #Is Simple?
  is.simple(simplified_graph)
  
  #Plot the degree distribution of the vertices.
  hist(degree(simplified_graph))
  
  #Only filter to edges belonging to nodes with degree less than 200
  plot(cg[E(simplified_graph)[degree(simplified_graph) > 200]])
  
  #Estimate the betweenness score for nodes in the graph, the betweenness is the measure of how many shortests paths that a given node belongs to.
  betweenness(simplified_graph)
  
  #eigen_centrality(simplified_graph)
  
  #The Diameter represents the longest path in the graph.
  diameter(simplified_graph)
  
  #This function outputs the path of the diameter of the graph.
  get_diameter(simplified_graph)
  
  #Just plot the graph
  plot(simplified_graph)
  
  #Plot the graph using fruchterman reingold layout.
  plot(simplified_graph, layout.fruchterman.reingold.grid(simplified_graph, circular=T)) 
}

parseMainGraph(graphs)
```

### Process individual sub graph:
```{r}
processGraph <- function(gr){
  
  #Check if given graph is an igraph object, if not then create one.
  if(class(gr) != 'igraph') {
    gr = graph_from_data_frame(gr, directed=FALSE)
  }
  #Plot the graph:
  #plot(gr, layout=layout_with_fr(gr, niter=1000))
  #Largest Clique
  largest_cliques(gr)
  #Find Ego
  #ego(gr, 2)
  #Power Centrality
  #alpha_centrality(gr)
}


for (graph in graphs){
  processGraph(graph)
}
```
Visualize Largest Clique
```{r}
graph_1 <- graph_from_data_frame(graphs[[1]])

clique1 <- largest_cliques(graph_1)[[1]]

plot(graph_1)

# subset the original graph by passing the clique vertices
g2 <- induced.subgraph(graph=graph_1,vids=clique1)

# plot the clique
plot(g2)
```

```{r}
clsnss = closeness(simplified_graph)
which.max(clsnss)
```