---
title: "Code"
author: "Pratheek Rebala"
date: "4/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
require(NLP)
library(stringr)
library('tm')
library(wordcloud)
data('acq')
```

Print word count of longest (by number of words) 15 documents.
```{r pressure, echo=FALSE}
t = data.frame()
for (doc in seq(1,length(acq))){
  currDoc = acq[doc]
  docTermMatrix <- as.matrix(DocumentTermMatrix(currDoc))
  t <- rbind(t, rowSums(docTermMatrix)[[1]])
}
top_15_documents <- tail(acq[order(t)], 15)

print('Word counts of the 15 longest documents')

for (doc in seq(1,15)){
  currDoc = top_15_documents[doc]
  docTermMatrix <- as.matrix(DocumentTermMatrix(currDoc))
  print(rowSums(docTermMatrix)[[1]])
}
```

```{r}
term_doc_matrix <- TermDocumentMatrix(acq, control = list(wordLengths = c(1, Inf)))
term_doc_matrix

tdm2 <- removeSparseTerms(term_doc_matrix, sparse=0.70)

distMatrix <- dist(scale(tdm2))
distMatrix

plot(hclust(distMatrix, method = "ward.D2"))
```

## 
```{r}
m1 <- as.matrix(tdm2)
word.freq <- sort(rowSums(m1), decreasing = T)

pal <- brewer.pal(9, 'BuGn')
pal <- pal[-(1:4)]
wordcloud(words = names(word.freq), freq = word.freq, min.freq = 3, random.order = F, colors = pal)
```

# Sentence Tokenizer & Print Longest 15 sentences
```{r}
## A simple text.
sentenceTokenizer <- function(s){
  sentences <- unlist(strsplit(s, '\\.(\\n|\\s)+', perl=TRUE))
  return(sentences)
}

longestSentences <- function(doc){
  sentences <- sentenceTokenizer(doc$content)
  return(sentences[order(nchar(sentences), decreasing=TRUE)])
}

all_sentences = list()

for (doc in seq(1,length(acq))){
  document = acq[[doc]]
  all_sentences <- rbind(all_sentences, longestSentences(document)[1])
}

all_sentences[order(nchar(all_sentences), decreasing=TRUE)][1:15]
```

# Print Data Frame of Sentences, Length and Document
```{r}
all_sentences = data.frame()

for (doc in seq(1,length(acq))){
  document = acq[[doc]]
  longest_sentences = longestSentences(document)
  sentence_lengths = data.frame(nchar(longest_sentences), longest_sentences)
  sentence_lengths$doc = doc
  all_sentences <- rbind(all_sentences, sentence_lengths)
}
names(all_sentences) <- c('length', 'sentence', 'document')

all_sentences
```

# No Punctuation
```{r}
print(removePunctuation(as.character(all_sentences$sentence)))
```